import sbtcrossproject.CrossPlugin.autoImport.{crossProject, CrossType}

// sbt 2 notes (from the walking skeleton): `%%` picks the platform suffix (`%%%` is gone), and a background build
// server started earlier doesn't see the client's environment, so local switches are command aliases. CI starts a
// fresh server per job, so reading `CI` there is safe.

ThisBuild / scalaVersion := "3.9.0"
ThisBuild / version := "0.1.0-SNAPSHOT"
ThisBuild / scalacOptions ++= Seq(
  "-deprecation",
  "-feature",
  "-Wunused:all",
  "-Wvalue-discard",
  "-Wnonunit-statement"
) ++ (if sys.env.contains("CI") then Seq("-Werror") else Nil)

val catsEffectV = "3.7.1"
val circeV = "0.14.16"
val fs2V = "3.14.0"
val http4sV = "0.23.37"
val laikaV = "1.3.2"
val sttpV = "4.0.26"
val tapirV = "1.13.31"

val testDependencies = Seq(
  "org.scalameta" %% "munit" % "1.3.6" % Test,
  "org.typelevel" %% "munit-cats-effect" % "2.2.0" % Test
)

// A clang installed by swiftly can shadow Apple's on PATH without the SDK headers; use the xcrun shim on macOS.
val pinAppleClang = nativeConfig ~= { config =>
  val appleClang = file("/usr/bin/clang")
  if sys.props("os.name").startsWith("Mac") && appleClang.exists then
    config.withClang(appleClang.toPath).withClangPP(file("/usr/bin/clang++").toPath)
  else config
}

lazy val root = project
  .in(file("."))
  .aggregate(
    shared.jvm,
    shared.js,
    shared.native,
    prose.jvm,
    prose.js,
    core,
    daemon,
    ui,
    cli.jvm,
    cli.native
  )

// The contract: domain types, tapir endpoints, codecs, query parser, text renderer, line diff. No business logic.
lazy val shared = crossProject(JVMPlatform, JSPlatform, NativePlatform)
  .crossType(CrossType.Pure)
  .in(file("shared"))
  .settings(
    libraryDependencies ++= Seq(
      "io.circe" %% "circe-core" % circeV,
      "io.circe" %% "circe-parser" % circeV,
      "com.softwaremill.sttp.tapir" %% "tapir-core" % tapirV,
      "com.softwaremill.sttp.tapir" %% "tapir-json-circe" % tapirV
    ) ++ testDependencies,
    Compile / sourceGenerators += Def.task {
      val file = (Compile / sourceManaged).value / "tikka" / "shared" / "BuildVersion.scala"
      IO.write(
        file,
        s"""package tikka.shared
           |
           |/** Generated by the build from its `version` setting. */
           |object BuildVersion:
           |  val current: Version = Version("${version.value}")
           |""".stripMargin
      )
      Seq(file)
    }.taskValue
  )
  .nativeSettings(pinAppleClang)

// Laika has no Scala Native build, so markdown lives here: mention detection (daemon) and rendering (UI).
lazy val prose = crossProject(JVMPlatform, JSPlatform)
  .crossType(CrossType.Pure)
  .in(file("prose"))
  .settings(
    libraryDependencies ++= Seq(
      "org.typelevel" %% "laika-core" % laikaV
    ) ++ testDependencies
  )

lazy val core = project
  .in(file("core"))
  .dependsOn(shared.jvm, prose.jvm)
  .settings(
    libraryDependencies ++= Seq(
      "co.fs2" %% "fs2-core" % fs2V,
      "org.tpolecat" %% "doobie-core" % "1.0.0-RC12",
      "org.xerial" % "sqlite-jdbc" % "3.53.4.0"
    ) ++ testDependencies
  )

lazy val daemon = project
  .in(file("daemon"))
  .dependsOn(core)
  .settings(
    libraryDependencies ++= Seq(
      "com.softwaremill.sttp.tapir" %% "tapir-http4s-server" % tapirV,
      "org.http4s" %% "http4s-ember-server" % http4sV,
      "org.http4s" %% "http4s-dsl" % http4sV,
      "org.http4s" %% "http4s-circe" % http4sV
    ) ++ testDependencies,
    fork := true,
    // sqlite-jdbc loads native code, which JDK 22+ warns about without this.
    javaOptions += "--enable-native-access=ALL-UNNAMED",
    // sbt 2 exports virtual classpaths, so the daemon runs from an assembly jar.
    assembly / mainClass := Some("tikka.daemon.Main"),
    // A fixed path, independent of the Scala version, for CI and installation.
    assembly / assemblyOutputPath := (LocalRootProject / baseDirectory).value / "target" / "dist" / "tikka-daemon.jar",
    assembly / assemblyMergeStrategy := {
      case PathList("META-INF", "versions", _, "module-info.class") => MergeStrategy.discard
      case PathList("module-info.class")                            => MergeStrategy.discard
      case other                                                    => (assembly / assemblyMergeStrategy).value(other)
    },
    // Production UI: the fullLinkJS output is embedded in the jar under /ui.
    Compile / resourceGenerators += Def.task {
      val linked = (ui / Compile / fullLinkJSOutput).value
      val dest = (Compile / resourceManaged).value / "ui"
      IO.copyDirectory(linked, dest)
      (dest ** "*").get().filter(_.isFile)
    }.taskValue
  )

lazy val ui = project
  .in(file("ui"))
  .enablePlugins(ScalaJSPlugin)
  .dependsOn(shared.js, prose.js)
  .settings(
    scalaJSUseMainModuleInitializer := true,
    libraryDependencies ++= Seq(
      "com.raquo" %% "laminar" % "18.0.0-M5",
      "com.raquo" %% "waypoint" % "10.0.0-M7",
      "com.softwaremill.sttp.tapir" %% "tapir-sttp-client4" % tapirV
    ) ++ testDependencies
  )

// Development runs on the JVM; Native links in CI, at install and for the startup gate.
lazy val cli = crossProject(JVMPlatform, NativePlatform)
  .crossType(CrossType.Full)
  .in(file("cli"))
  .dependsOn(shared)
  .settings(
    libraryDependencies ++= Seq(
      "org.typelevel" %% "cats-effect" % catsEffectV,
      "com.softwaremill.sttp.tapir" %% "tapir-sttp-client4" % tapirV,
      "com.softwaremill.sttp.client4" %% "cats" % sttpV
    ) ++ testDependencies
  )
  .jvmSettings(
    fork := true
  )
  .nativeSettings(
    pinAppleClang,
    nativeConfig ~= (_.withBaseName("tikka"))
  )

// Links the release CLI binary (the startup gate measures this build), then drops the `set` so later links in the same
// sbt server go back to debug mode.
addCommandAlias(
  "cliRelease",
  "set cli.native / nativeConfig ~= (_.withMode(scala.scalanative.build.Mode.releaseFast).withLTO(scala.scalanative.build.LTO.thin)); cliNative / nativeLink; session clear-all"
)
